### GET request with a header
GET {{BASE_URL}}/ip
Accept: application/json

### GET request with parameter
GET {{BASE_URL}}/get?show_env=1
Accept: application/json

> {% client.global.set("show_env", response.body.args.show_env); %}

### GET request with environment variables
GET {{BASE_URL}}/get?show_env={{show_env}}
Accept: application/json

### GET request with disabled redirects
# @no-redirect
GET {{BASE_URL}}/status/301

### GET request with dynamic variables
GET {{BASE_URL}}/anything?id={{$uuid}}&ts={{$timestamp}}